<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="diva" ignored="0" name="Test" tests="9" failures="2" timestamp="24 Nov 2021 19:23:10 GMT" time="0.125" errors="0">
  <testcase name="tc1" time="0.016" classname="org.testing.Rerunfail1">
    <skipped/>
  </testcase> <!-- tc1 -->
  <testcase name="tc1" time="0.0" classname="org.testing.Rerunfail1">
    <skipped/>
  </testcase> <!-- tc1 -->
  <testcase name="tc1" time="0.0" classname="org.testing.Rerunfail1">
    <skipped/>
  </testcase> <!-- tc1 -->
  <testcase name="tc1" time="0.0" classname="org.testing.Rerunfail1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testing.Rerunfail1.tc1(Rerunfail1.java:10)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tc1 -->
  <testcase name="tc2" time="0.0" classname="org.testing.Rerunfail1"/>
  <testcase name="tc3" time="0.0" classname="org.testing.Rerunfail1">
    <skipped/>
  </testcase> <!-- tc3 -->
  <testcase name="tc3" time="0.016" classname="org.testing.Rerunfail1">
    <skipped/>
  </testcase> <!-- tc3 -->
  <testcase name="tc3" time="0.0" classname="org.testing.Rerunfail1">
    <skipped/>
  </testcase> <!-- tc3 -->
  <testcase name="tc3" time="0.016" classname="org.testing.Rerunfail1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testing.Rerunfail1.tc3(Rerunfail1.java:24)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tc3 -->
</testsuite> <!-- Test -->
